#!/usr/bin/env python3
"""把 web/index.html 内联生成为 web_assets.go。

原因：当前构建环境的 Go 工具链未启用 //go:embed 指令，
因此改为把 HTML 直接作为 Go 字符串常量内联，保证二进制自包含。
修改 web/index.html 后重新运行本脚本即可。
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "web", "index.html")
OUT = os.path.join(HERE, "web_assets.go")


def main():
    with open(SRC, "r", encoding="utf-8") as f:
        html = f.read()
    # json.dumps 生成的双引号字符串对 Go 同样合法（\uXXXX / \" / \\ 等）。
    lit = json.dumps(html, ensure_ascii=False)
    content = (
        "// Code generated by gen_assets.py. DO NOT EDIT.\n"
        "package main\n\n"
        "// indexHTML 是 Web 管理界面的内联 HTML。\n"
        "var indexHTML = []byte(" + lit + ")\n"
    )
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(content)
    print("written", OUT, "(", len(html), "bytes html )")


if __name__ == "__main__":
    main()
